# Generated by Django 4.2.8 on 2024-04-29 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("deals", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deals",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Сделка",
            ),
        ),
    ]
