version: '3.3'

volumes:
  pg_data:
  static:

services:

  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ../lendme_api/
    env_file: ../.env
    depends_on:
      - db
    volumes:
      - static:/backend_static

  frontend:
    build: ../frontend/
    env_file: ../.env

  nginx:
    image: nginx:1.22.1
    depends_on:
      - db
      - backend
      - frontend
    ports:
      - '8000:80'
    volumes:
      - static:/staticfiles/
