# Generated by Django 4.2.8 on 2024-05-02 06:57

import django.core.validators
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=12,
                region="RU",
                unique=True,
                validators=[django.core.validators.MinLengthValidator(12)],
                verbose_name="Номер телефон",
            ),
        ),
    ]
