# Generated by Django 4.2.8 on 2024-05-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_name_authtransaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authtransaction",
            options={
                "verbose_name": "Транзакция аутентификации",
                "verbose_name_plural": "Транзакции аутентификаций",
            },
        ),
        migrations.AddField(
            model_name="authtransaction",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Город"
            ),
        ),
        migrations.AlterField(
            model_name="authtransaction",
            name="create_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="authtransaction",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата окончания"
            ),
        ),
        migrations.AlterField(
            model_name="authtransaction",
            name="refresh_token",
            field=models.TextField(blank=True, verbose_name="JWT Refresh Token"),
        ),
        migrations.AlterField(
            model_name="authtransaction",
            name="session",
            field=models.TextField(verbose_name="Session"),
        ),
        migrations.AlterField(
            model_name="authtransaction",
            name="token",
            field=models.TextField(verbose_name="JWT Access Token"),
        ),
        migrations.AlterField(
            model_name="authtransaction",
            name="update_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
    ]
