# Generated by Django 4.2.8 on 2024-05-30 11:47

import django.contrib.auth.tokens
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_emailconfirmationtoken_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=50, unique=True, verbose_name="Юзернейм"),
        ),
        migrations.AlterField(
            model_name="emailconfirmationtoken",
            name="token",
            field=models.CharField(
                default=django.contrib.auth.tokens.PasswordResetTokenGenerator.make_token,
                max_length=64,
            ),
        ),
    ]
