# Generated by Django 4.2.8 on 2024-05-01 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_authtransaction_options_authtransaction_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.IntegerField(
                max_length=10,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(10)],
                verbose_name="Номер телефон",
            ),
        ),
    ]
